- name: Asegurar si mariadb esta instalado
  apt:
    pkg:
      - mariadb-server
      - python-mysqldb
    state: latest
- name: Creacion de la base de datos
  mysql_db: name={{ wordpress_db }}

- name: Creacion del usuario en la base de datos
  mysql_user:
    name: "{{ wordpress_user }}"
    password: "{{ wordpress_pass }}"
    priv: "{{ wordpress_db }}.*:ALL"
    host: '%'

- name: transfiriendo configuracion mariadb
  template: >-
    src=etc/mysql/mariadb.conf.d/50-server.cnf
    dest=/etc/mysql/mariadb.conf.d/50-server.cnf
    owner=root
    group=root
    mode=644
  notify:
      restart mariadb
